"""
send_email.py
Gmail経由でマーケットレポート（PDF添付）を送信する
jibun-os-hub/reports/ に配置して使用する
"""

import os
import glob
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders


def main():
    gmail_user     = os.environ["GMAIL_USER"]
    gmail_password = os.environ["GMAIL_APP_PASSWORD"]
    recipient      = os.environ["REPORT_RECIPIENT"]

    today = datetime.now().strftime("%Y年%m月%d日")

    # Drive URL を取得（upload_drive.py が生成）
    drive_link = ""
    link_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "drive_link.txt")
    if os.path.exists(link_path):
        with open(link_path) as f:
            drive_link = f.read().strip()

    # 最新 PDF を探す
    script_dir  = os.path.dirname(os.path.abspath(__file__))
    output_dir  = os.path.join(script_dir, "output")
    files       = sorted(glob.glob(os.path.join(output_dir, "*.pdf")))
    report_file = files[-1] if files else None

    if not report_file:
        print("⚠️  警告: output/*.pdf が見つかりません。添付なしで送信します。")

    # ── HTML メール本文 ──────────────────────────────────────
    drive_button = ""
    if drive_link:
        drive_button = f"""
    <div style="text-align: center; margin: 24px 0;">
      <a href="{drive_link}"
         style="background: #1B3A5C; color: white; padding: 12px 28px;
                text-decoration: none; border-radius: 4px; font-size: 14px;
                display: inline-block;">
        📁 Google Drive で PDF を開く
      </a>
    </div>"""

    html_body = f"""
<html>
<body style="font-family: Arial, sans-serif; color: #1A1A1A; max-width: 640px; margin: 0 auto;">

  <!-- ヘッダー -->
  <div style="background: #0D1B2A; padding: 24px 28px; border-bottom: 3px solid #C9A84C;">
    <p style="color: #F5E6C8; font-size: 11px; margin: 0 0 6px; letter-spacing: 1px;">
      MARKET DAILY REPORT — ai-jidoka-keigo.com
    </p>
    <h1 style="color: #FFFFFF; font-size: 20px; margin: 0; line-height: 1.4;">
      マーケット デイリー レポート
    </h1>
    <p style="color: #C9A84C; font-size: 13px; margin: 8px 0 0;">{today} 発行</p>
  </div>

  <!-- 本文 -->
  <div style="padding: 24px 28px; background: #F9F9F9;">
    <p style="margin: 0 0 16px;">おはようございます。</p>
    <p style="margin: 0 0 16px;">
      本日（{today}）のマーケット デイリー レポートをお届けします。
    </p>

    <!-- 対象銘柄 -->
    <div style="background: #FFFFFF; border-left: 4px solid #1B3A5C;
                padding: 16px 20px; margin: 16px 0; border-radius: 0 4px 4px 0;">
      <h3 style="color: #1B3A5C; margin: 0 0 10px; font-size: 14px;">
        📊 本日の追跡銘柄
      </h3>
      <ul style="margin: 0; padding-left: 20px; font-size: 13px; line-height: 1.8;">
        <li>トクヤマ（4043・東証P）― 半導体多結晶シリコン</li>
        <li>リガク・ホールディングス（268A・東証P）― X線分析装置</li>
        <li>Marvell Technology（MRVL・NASDAQ）― AIカスタムシリコン</li>
        <li>KIOXIA HD（285A・東証P）― NAND型フラッシュメモリ</li>
      </ul>
    </div>

    {drive_button}

    <p style="font-size: 11px; color: #999; margin: 16px 0 0; line-height: 1.8;">
      ※ PDFレポートを添付しています。<br>
      ※ 本メールは自動送信です。返信しても届きません。
    </p>
  </div>

  <!-- フッター -->
  <div style="padding: 14px 28px; background: #EEEEEE;
              font-size: 10px; color: #999; line-height: 1.7;">
    本レポートはすべて情報提供のみを目的とした参考資料であり、
    特定の有価証券の売買を推奨・勧誘するものではありません。
    投資判断はご自身の責任において行ってください。<br>
    Generated by Claude AI / ai-jidoka-keigo.com
  </div>

</body>
</html>
"""

    # ── メール組み立て ────────────────────────────────────────
    msg = MIMEMultipart("mixed")
    msg["Subject"] = f"【マーケットレポート】{today}"
    msg["From"]    = gmail_user
    msg["To"]      = recipient

    msg.attach(MIMEText(html_body, "html", "utf-8"))

    # PDF 添付
    if report_file:
        with open(report_file, "rb") as f:
            part = MIMEBase("application", "pdf")
            part.set_payload(f.read())
        encoders.encode_base64(part)
        filename = os.path.basename(report_file)
        part.add_header("Content-Disposition", f'attachment; filename="{filename}"')
        msg.attach(part)

    # ── 送信 ─────────────────────────────────────────────────
    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(gmail_user, gmail_password)
        server.sendmail(gmail_user, recipient, msg.as_string())

    print(f"✅ メール送信完了 → {recipient}")
    if report_file:
        print(f"   添付: {os.path.basename(report_file)}")
    else:
        print("   添付: なし")


if __name__ == "__main__":
    main()
